window.esdocSearchIndex = [
  [
    "stencila-convert/src/document/documentconverter.js~documentconverter",
    "class/src/document/DocumentConverter.js~DocumentConverter.html",
    "<span>DocumentConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentdocxconverter.js~documentdocxconverter",
    "class/src/document/DocumentDocxConverter.js~DocumentDocxConverter.html",
    "<span>DocumentDocxConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentDocxConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documenthtmlconverter.js~documenthtmlconverter",
    "class/src/document/DocumentHtmlConverter.js~DocumentHtmlConverter.html",
    "<span>DocumentHtmlConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentHtmlConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentjupyterconverter.js~documentjupyterconverter",
    "class/src/document/DocumentJupyterConverter.js~DocumentJupyterConverter.html",
    "<span>DocumentJupyterConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentJupyterConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentlatexconverter.js~documentlatexconverter",
    "class/src/document/DocumentLatexConverter.js~DocumentLatexConverter.html",
    "<span>DocumentLatexConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentLatexConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentmdconverter.js~documentmdconverter",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html",
    "<span>DocumentMdConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentMdConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentodtconverter.js~documentodtconverter",
    "class/src/document/DocumentOdtConverter.js~DocumentOdtConverter.html",
    "<span>DocumentOdtConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentOdtConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentpandocconverter.js~documentpandocconverter",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html",
    "<span>DocumentPandocConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentPandocConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentpdfconverter.js~documentpdfconverter",
    "class/src/document/DocumentPdfConverter.js~DocumentPdfConverter.html",
    "<span>DocumentPdfConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentPdfConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentrmdconverter.js~documentrmdconverter",
    "class/src/document/DocumentRmdConverter.js~DocumentRmdConverter.html",
    "<span>DocumentRmdConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentRmdConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/document/documentxmdconverter.js~documentxmdconverter",
    "class/src/document/DocumentXmdConverter.js~DocumentXmdConverter.html",
    "<span>DocumentXmdConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/document/DocumentXmdConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/project/projectconverter.js~projectconverter",
    "class/src/project/ProjectConverter.js~ProjectConverter.html",
    "<span>ProjectConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/project/ProjectConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/project/projectfolderconverter.js~projectfolderconverter",
    "class/src/project/ProjectFolderConverter.js~ProjectFolderConverter.html",
    "<span>ProjectFolderConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/project/ProjectFolderConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/sheet/sheetconverter.js~sheetconverter",
    "class/src/sheet/SheetConverter.js~SheetConverter.html",
    "<span>SheetConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/sheet/SheetConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/sheet/sheetdsvconverter.js~sheetdsvconverter",
    "class/src/sheet/SheetDSVConverter.js~SheetDSVConverter.html",
    "<span>SheetDSVConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/sheet/SheetDSVConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/sheet/sheetodsconverter.js~sheetodsconverter",
    "class/src/sheet/SheetODSConverter.js~SheetODSConverter.html",
    "<span>SheetODSConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/sheet/SheetODSConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/sheet/sheetscriptconverter.js~sheetscriptconverter",
    "class/src/sheet/SheetScriptConverter.js~SheetScriptConverter.html",
    "<span>SheetScriptConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/sheet/SheetScriptConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/sheet/sheettdpconverter.js~sheettdpconverter",
    "class/src/sheet/SheetTDPConverter.js~SheetTDPConverter.html",
    "<span>SheetTDPConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/sheet/SheetTDPConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/sheet/sheetxlsxconverter.js~sheetxlsxconverter",
    "class/src/sheet/SheetXLSXConverter.js~SheetXLSXConverter.html",
    "<span>SheetXLSXConverter</span> <span class=\"search-result-import-path\">stencila-convert/src/sheet/SheetXLSXConverter.js</span>",
    "class"
  ],
  [
    "stencila-convert/src/helpers/pandoc.js~pandoc",
    "variable/index.html#static-variable-pandoc",
    "<span>pandoc</span> <span class=\"search-result-import-path\">stencila-convert/src/helpers/pandoc.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/document/documentconverter.js",
    "file/src/document/DocumentConverter.js.html",
    "src/document/DocumentConverter.js",
    "file"
  ],
  [
    "src/document/documentconverter.js~documentconverter#extensions",
    "class/src/document/DocumentConverter.js~DocumentConverter.html#instance-method-extensions",
    "src/document/DocumentConverter.js~DocumentConverter#extensions",
    "method"
  ],
  [
    "src/document/documentdocxconverter.js",
    "file/src/document/DocumentDocxConverter.js.html",
    "src/document/DocumentDocxConverter.js",
    "file"
  ],
  [
    "src/document/documentdocxconverter.js~documentdocxconverter#pandocexportargs",
    "class/src/document/DocumentDocxConverter.js~DocumentDocxConverter.html#instance-method-pandocExportArgs",
    "src/document/DocumentDocxConverter.js~DocumentDocxConverter#pandocExportArgs",
    "method"
  ],
  [
    "src/document/documentdocxconverter.js~documentdocxconverter#pandocformat",
    "class/src/document/DocumentDocxConverter.js~DocumentDocxConverter.html#instance-method-pandocFormat",
    "src/document/DocumentDocxConverter.js~DocumentDocxConverter#pandocFormat",
    "method"
  ],
  [
    "src/document/documenthtmlconverter.js",
    "file/src/document/DocumentHtmlConverter.js.html",
    "src/document/DocumentHtmlConverter.js",
    "file"
  ],
  [
    "src/document/documenthtmlconverter.js~documenthtmlconverter#pandocformat",
    "class/src/document/DocumentHtmlConverter.js~DocumentHtmlConverter.html#instance-method-pandocFormat",
    "src/document/DocumentHtmlConverter.js~DocumentHtmlConverter#pandocFormat",
    "method"
  ],
  [
    "src/document/documentjupyterconverter.js",
    "file/src/document/DocumentJupyterConverter.js.html",
    "src/document/DocumentJupyterConverter.js",
    "file"
  ],
  [
    "src/document/documentjupyterconverter.js~documentjupyterconverter#extensions",
    "class/src/document/DocumentJupyterConverter.js~DocumentJupyterConverter.html#instance-method-extensions",
    "src/document/DocumentJupyterConverter.js~DocumentJupyterConverter#extensions",
    "method"
  ],
  [
    "src/document/documentjupyterconverter.js~documentjupyterconverter#import",
    "class/src/document/DocumentJupyterConverter.js~DocumentJupyterConverter.html#instance-method-import",
    "src/document/DocumentJupyterConverter.js~DocumentJupyterConverter#import",
    "method"
  ],
  [
    "src/document/documentlatexconverter.js",
    "file/src/document/DocumentLatexConverter.js.html",
    "src/document/DocumentLatexConverter.js",
    "file"
  ],
  [
    "src/document/documentlatexconverter.js~documentlatexconverter#extensions",
    "class/src/document/DocumentLatexConverter.js~DocumentLatexConverter.html#instance-method-extensions",
    "src/document/DocumentLatexConverter.js~DocumentLatexConverter#extensions",
    "method"
  ],
  [
    "src/document/documentlatexconverter.js~documentlatexconverter#pandocformat",
    "class/src/document/DocumentLatexConverter.js~DocumentLatexConverter.html#instance-method-pandocFormat",
    "src/document/DocumentLatexConverter.js~DocumentLatexConverter#pandocFormat",
    "method"
  ],
  [
    "src/document/documentmdconverter.js",
    "file/src/document/DocumentMdConverter.js.html",
    "src/document/DocumentMdConverter.js",
    "file"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#export",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-export",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#export",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#extensions",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-extensions",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#extensions",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#import",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-import",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#import",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#pandocexportargs",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-pandocExportArgs",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#pandocExportArgs",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#pandocexportformat",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-pandocExportFormat",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#pandocExportFormat",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#pandocexporttemplate",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-pandocExportTemplate",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#pandocExportTemplate",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#pandocimportargs",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-pandocImportArgs",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#pandocImportArgs",
    "method"
  ],
  [
    "src/document/documentmdconverter.js~documentmdconverter#pandocimportformat",
    "class/src/document/DocumentMdConverter.js~DocumentMdConverter.html#instance-method-pandocImportFormat",
    "src/document/DocumentMdConverter.js~DocumentMdConverter#pandocImportFormat",
    "method"
  ],
  [
    "src/document/documentodtconverter.js",
    "file/src/document/DocumentOdtConverter.js.html",
    "src/document/DocumentOdtConverter.js",
    "file"
  ],
  [
    "src/document/documentodtconverter.js~documentodtconverter#pandocexportargs",
    "class/src/document/DocumentOdtConverter.js~DocumentOdtConverter.html#instance-method-pandocExportArgs",
    "src/document/DocumentOdtConverter.js~DocumentOdtConverter#pandocExportArgs",
    "method"
  ],
  [
    "src/document/documentodtconverter.js~documentodtconverter#pandocformat",
    "class/src/document/DocumentOdtConverter.js~DocumentOdtConverter.html#instance-method-pandocFormat",
    "src/document/DocumentOdtConverter.js~DocumentOdtConverter#pandocFormat",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js",
    "file/src/document/DocumentPandocConverter.js.html",
    "src/document/DocumentPandocConverter.js",
    "file"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#_convert",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-_convert",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#_convert",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#canexport",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-canExport",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#canExport",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#canimport",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-canImport",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#canImport",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#export",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-export",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#export",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#extensions",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-extensions",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#extensions",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#import",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-import",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#import",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#pandocexportargs",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-pandocExportArgs",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#pandocExportArgs",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#pandocexportformat",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-pandocExportFormat",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#pandocExportFormat",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#pandocexporttemplate",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-pandocExportTemplate",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#pandocExportTemplate",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#pandocformat",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-pandocFormat",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#pandocFormat",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#pandocimportargs",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-pandocImportArgs",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#pandocImportArgs",
    "method"
  ],
  [
    "src/document/documentpandocconverter.js~documentpandocconverter#pandocimportformat",
    "class/src/document/DocumentPandocConverter.js~DocumentPandocConverter.html#instance-method-pandocImportFormat",
    "src/document/DocumentPandocConverter.js~DocumentPandocConverter#pandocImportFormat",
    "method"
  ],
  [
    "src/document/documentpdfconverter.js",
    "file/src/document/DocumentPdfConverter.js.html",
    "src/document/DocumentPdfConverter.js",
    "file"
  ],
  [
    "src/document/documentpdfconverter.js~documentpdfconverter#canexport",
    "class/src/document/DocumentPdfConverter.js~DocumentPdfConverter.html#instance-method-canExport",
    "src/document/DocumentPdfConverter.js~DocumentPdfConverter#canExport",
    "method"
  ],
  [
    "src/document/documentpdfconverter.js~documentpdfconverter#canimport",
    "class/src/document/DocumentPdfConverter.js~DocumentPdfConverter.html#instance-method-canImport",
    "src/document/DocumentPdfConverter.js~DocumentPdfConverter#canImport",
    "method"
  ],
  [
    "src/document/documentpdfconverter.js~documentpdfconverter#pandocexportargs",
    "class/src/document/DocumentPdfConverter.js~DocumentPdfConverter.html#instance-method-pandocExportArgs",
    "src/document/DocumentPdfConverter.js~DocumentPdfConverter#pandocExportArgs",
    "method"
  ],
  [
    "src/document/documentrmdconverter.js",
    "file/src/document/DocumentRmdConverter.js.html",
    "src/document/DocumentRmdConverter.js",
    "file"
  ],
  [
    "src/document/documentrmdconverter.js~documentrmdconverter#extensions",
    "class/src/document/DocumentRmdConverter.js~DocumentRmdConverter.html#instance-method-extensions",
    "src/document/DocumentRmdConverter.js~DocumentRmdConverter#extensions",
    "method"
  ],
  [
    "src/document/documentxmdconverter.js",
    "file/src/document/DocumentXmdConverter.js.html",
    "src/document/DocumentXmdConverter.js",
    "file"
  ],
  [
    "src/document/documentxmdconverter.js~documentxmdconverter#_comment",
    "class/src/document/DocumentXmdConverter.js~DocumentXmdConverter.html#instance-method-_comment",
    "src/document/DocumentXmdConverter.js~DocumentXmdConverter#_comment",
    "method"
  ],
  [
    "src/document/documentxmdconverter.js~documentxmdconverter#_shortname",
    "class/src/document/DocumentXmdConverter.js~DocumentXmdConverter.html#instance-method-_shortname",
    "src/document/DocumentXmdConverter.js~DocumentXmdConverter#_shortname",
    "method"
  ],
  [
    "src/document/documentxmdconverter.js~documentxmdconverter#export",
    "class/src/document/DocumentXmdConverter.js~DocumentXmdConverter.html#instance-method-export",
    "src/document/DocumentXmdConverter.js~DocumentXmdConverter#export",
    "method"
  ],
  [
    "src/document/documentxmdconverter.js~documentxmdconverter#import",
    "class/src/document/DocumentXmdConverter.js~DocumentXmdConverter.html#instance-method-import",
    "src/document/DocumentXmdConverter.js~DocumentXmdConverter#import",
    "method"
  ],
  [
    "src/document/index.js",
    "file/src/document/index.js.html",
    "src/document/index.js",
    "file"
  ],
  [
    "src/helpers/index.js",
    "file/src/helpers/index.js.html",
    "src/helpers/index.js",
    "file"
  ],
  [
    "src/helpers/pandoc.js",
    "file/src/helpers/pandoc.js.html",
    "src/helpers/pandoc.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/project/projectconverter.js",
    "file/src/project/ProjectConverter.js.html",
    "src/project/ProjectConverter.js",
    "file"
  ],
  [
    "src/project/projectconverter.js~projectconverter#converters",
    "class/src/project/ProjectConverter.js~ProjectConverter.html#instance-get-converters",
    "src/project/ProjectConverter.js~ProjectConverter#converters",
    "member"
  ],
  [
    "src/project/projectconverter.js~projectconverter#createdom",
    "class/src/project/ProjectConverter.js~ProjectConverter.html#instance-method-createDom",
    "src/project/ProjectConverter.js~ProjectConverter#createDom",
    "method"
  ],
  [
    "src/project/projectfolderconverter.js",
    "file/src/project/ProjectFolderConverter.js.html",
    "src/project/ProjectFolderConverter.js",
    "file"
  ],
  [
    "src/project/projectfolderconverter.js~projectfolderconverter#canimport",
    "class/src/project/ProjectFolderConverter.js~ProjectFolderConverter.html#instance-method-canImport",
    "src/project/ProjectFolderConverter.js~ProjectFolderConverter#canImport",
    "method"
  ],
  [
    "src/project/projectfolderconverter.js~projectfolderconverter#import",
    "class/src/project/ProjectFolderConverter.js~ProjectFolderConverter.html#instance-method-import",
    "src/project/ProjectFolderConverter.js~ProjectFolderConverter#import",
    "method"
  ],
  [
    "src/project/index.js",
    "file/src/project/index.js.html",
    "src/project/index.js",
    "file"
  ],
  [
    "src/sheet/sheetconverter.js",
    "file/src/sheet/SheetConverter.js.html",
    "src/sheet/SheetConverter.js",
    "file"
  ],
  [
    "src/sheet/sheetconverter.js~sheetconverter#createdom",
    "class/src/sheet/SheetConverter.js~SheetConverter.html#instance-method-createDom",
    "src/sheet/SheetConverter.js~SheetConverter#createDom",
    "method"
  ],
  [
    "src/sheet/sheetconverter.js~sheetconverter#export",
    "class/src/sheet/SheetConverter.js~SheetConverter.html#instance-method-export",
    "src/sheet/SheetConverter.js~SheetConverter#export",
    "method"
  ],
  [
    "src/sheet/sheetconverter.js~sheetconverter#import",
    "class/src/sheet/SheetConverter.js~SheetConverter.html#instance-method-import",
    "src/sheet/SheetConverter.js~SheetConverter#import",
    "method"
  ],
  [
    "src/sheet/sheetdsvconverter.js",
    "file/src/sheet/SheetDSVConverter.js.html",
    "src/sheet/SheetDSVConverter.js",
    "file"
  ],
  [
    "src/sheet/sheetdsvconverter.js~sheetdsvconverter#canimport",
    "class/src/sheet/SheetDSVConverter.js~SheetDSVConverter.html#instance-method-canImport",
    "src/sheet/SheetDSVConverter.js~SheetDSVConverter#canImport",
    "method"
  ],
  [
    "src/sheet/sheetdsvconverter.js~sheetdsvconverter#import",
    "class/src/sheet/SheetDSVConverter.js~SheetDSVConverter.html#instance-method-import",
    "src/sheet/SheetDSVConverter.js~SheetDSVConverter#import",
    "method"
  ],
  [
    "src/sheet/sheetodsconverter.js",
    "file/src/sheet/SheetODSConverter.js.html",
    "src/sheet/SheetODSConverter.js",
    "file"
  ],
  [
    "src/sheet/sheetodsconverter.js~sheetodsconverter#canimport",
    "class/src/sheet/SheetODSConverter.js~SheetODSConverter.html#instance-method-canImport",
    "src/sheet/SheetODSConverter.js~SheetODSConverter#canImport",
    "method"
  ],
  [
    "src/sheet/sheetscriptconverter.js",
    "file/src/sheet/SheetScriptConverter.js.html",
    "src/sheet/SheetScriptConverter.js",
    "file"
  ],
  [
    "src/sheet/sheetscriptconverter.js~sheetscriptconverter#export",
    "class/src/sheet/SheetScriptConverter.js~SheetScriptConverter.html#instance-method-export",
    "src/sheet/SheetScriptConverter.js~SheetScriptConverter#export",
    "method"
  ],
  [
    "src/sheet/sheetscriptconverter.js~sheetscriptconverter#import",
    "class/src/sheet/SheetScriptConverter.js~SheetScriptConverter.html#instance-method-import",
    "src/sheet/SheetScriptConverter.js~SheetScriptConverter#import",
    "method"
  ],
  [
    "src/sheet/sheettdpconverter.js",
    "file/src/sheet/SheetTDPConverter.js.html",
    "src/sheet/SheetTDPConverter.js",
    "file"
  ],
  [
    "src/sheet/sheettdpconverter.js~sheettdpconverter#export",
    "class/src/sheet/SheetTDPConverter.js~SheetTDPConverter.html#instance-method-export",
    "src/sheet/SheetTDPConverter.js~SheetTDPConverter#export",
    "method"
  ],
  [
    "src/sheet/sheettdpconverter.js~sheettdpconverter#import",
    "class/src/sheet/SheetTDPConverter.js~SheetTDPConverter.html#instance-method-import",
    "src/sheet/SheetTDPConverter.js~SheetTDPConverter#import",
    "method"
  ],
  [
    "src/sheet/sheettdpconverter.js~sheettdpconverter#match",
    "class/src/sheet/SheetTDPConverter.js~SheetTDPConverter.html#instance-method-match",
    "src/sheet/SheetTDPConverter.js~SheetTDPConverter#match",
    "method"
  ],
  [
    "src/sheet/sheetxlsxconverter.js",
    "file/src/sheet/SheetXLSXConverter.js.html",
    "src/sheet/SheetXLSXConverter.js",
    "file"
  ],
  [
    "src/sheet/sheetxlsxconverter.js~sheetxlsxconverter#canimport",
    "class/src/sheet/SheetXLSXConverter.js~SheetXLSXConverter.html#instance-method-canImport",
    "src/sheet/SheetXLSXConverter.js~SheetXLSXConverter#canImport",
    "method"
  ],
  [
    "src/sheet/index.js",
    "file/src/sheet/index.js.html",
    "src/sheet/index.js",
    "file"
  ]
]